### ISSUE TITLE
Request please set the debug flag to False

### ISSUE THREAD

**Issue by Demayl** [tbrowder/Net-IP#3]
https://github.com/tbrowder/Net-IP-Perl6/blob/13bc2989f5e44befd90ba257691a6194347d9f4c/lib/Net/IP.rakumod#L30

**Comment by tbrowder** [comment]
Oops, sorry. I'll take care of it tomorrow. Thanks for catching it.

**Comment by tbrowder** [comment]
Closed with the v2.1.2 release. Thanks!
